"""Generate FHI-aims geometry.in files for every symmetry-distinct motif of
a given n×n hBN supercell with a specified defect count, optionally embedded
in a larger m×m host supercell.

Two enumeration algorithms (selectable with --algorithm):

  canonical (default)
    Enumerate canonical classes on the n×n sub-supercell under G(n) (cheap),
    pick a compact orbit representative, centre it inside the m×m host. The
    hash is computed on the n×n tensor and is stable across host sizes.

  window
    Enumerate all (k_B, k_N) placements inside the n×n corner window of the
    m×m host, deduplicated by the subset of G(m) whose action keeps the
    defect support inside the window (variant (B) — depends per-config, not
    a fixed subgroup). Hash is computed on the window-canonical 2n² slice
    and is *not* stable across m, because m×m PBC is genuinely different
    from n×n PBC. Produces strictly more classes than canonical when m > n.

Output paths:
    {OUT}/BN-{m}-{m}-1-pure/geometry.in          when k = 0
    {OUT}/BN-{n}-{n}-1-{label}/geometry.in       when m == n and k > 0
    {OUT}/BN-{m}-{m}-1-N{n}-{label}/geometry.in  when m > n and k > 0

Usage:
    python generate_geometry.py <n> <k> [out_dir] [m] [--algorithm {canonical,window}]

Generates all (k_B, k_N) splits with k_B + k_N = k.
OUT_DIR defaults to 'generated/'; m defaults to n (no embedding).
"""

import hashlib
import sys
from itertools import combinations
from pathlib import Path

import numpy as np

from canonicalize import (
    build_coords,
    build_group,
    enumerate_motifs,
    summary_label,
)
from tools.render_supercell import annotate, render_from_tensor


def parse_BN_in(path: Path) -> tuple[list, list]:
    """Return (lattice_vectors[3][3], atom_info[2]) where each atom is
    (species, frac_x, frac_y, frac_z)."""
    lattice = []
    atoms = []
    with open(path) as f:
        for line in f:
            parts = line.split()
            if not parts or parts[0].startswith("#"):
                continue
            if parts[0] == "lattice_vector":
                lattice.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "atom_frac":
                atoms.append((parts[4], float(parts[1]), float(parts[2]), float(parts[3])))
    assert len(lattice) == 3, f"Expected 3 lattice_vector lines, got {len(lattice)}"
    assert len(atoms) == 2, f"Expected 2 atoms in primitive BN.in, got {len(atoms)}"
    # Order atoms so that B comes first, N second (matches Maciej convention).
    atoms.sort(key=lambda a: 0 if a[0] == "B" else 1)
    return lattice, atoms


def write_geometry(
    out_path: Path,
    lattice: list,
    primitive_atoms: list,
    n: int,
    tensor,
    header: str = "",
):
    """Write a geometry.in for an n×n supercell with C substitutions per `tensor`.

    tensor: 1-D length 2n², with 1 at (channel, i, j) for each C.
      - channel 0 = B-sublattice substitution
      - channel 1 = N-sublattice substitution
    """
    (b_sp, b_fx, b_fy, b_fz), (n_sp, n_fx, n_fy, n_fz) = primitive_atoms
    assert b_sp == "B" and n_sp == "N"

    # Supercell lattice vectors (z untouched)
    a1 = [lattice[0][k] * n for k in range(3)]
    a2 = [lattice[1][k] * n for k in range(3)]
    a3 = lattice[2]

    lines = []
    if header:
        lines.append(f"# {header}")
    lines.append(f"# Generated by generate_geometry.py for n={n} supercell")
    lines.append("#")
    lines.append("# Supercell view (armchair-vertical, a₂ slants down-right):")
    for line in render_from_tensor(tensor, n).split("\n"):
        lines.append(f"#   {line}")
    for line in annotate(tensor=tensor, n=n).split("\n"):
        lines.append(f"# {line}")
    lines.append("#")
    for vec in (a1, a2, a3):
        lines.append(
            f"lattice_vector {vec[0]:18.10f} {vec[1]:18.10f} {vec[2]:18.10f}"
        )

    m = n * n
    for i in range(n):
        for j in range(n):
            # B at supercell-frac ((i + b_fx)/n, (j + b_fy)/n, b_fz)
            sp_B = "C" if tensor[i * n + j] else "B"
            fx_B = (i + b_fx) / n
            fy_B = (j + b_fy) / n
            lines.append(
                f"atom_frac      {fx_B:18.10f} {fy_B:18.10f} {b_fz:18.10f} {sp_B}"
            )
            sp_N = "C" if tensor[m + i * n + j] else "N"
            fx_N = (i + n_fx) / n
            fy_N = (j + n_fy) / n
            lines.append(
                f"atom_frac      {fx_N:18.10f} {fy_N:18.10f} {n_fz:18.10f} {sp_N}"
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


def _defect_site_ij(idx: int, n: int) -> tuple[int, int]:
    """Return the (i, j) cell index of a flat B/N defect-site index."""
    nsq = n * n
    site = idx if idx < nsq else idx - nsq
    return site // n, site % n


def _compactness_score(tensor: np.ndarray, n: int) -> tuple[float, float, int]:
    """Score a representative by non-periodic compactness. Lower is better.

    The first term catches motifs split across the artificial n×n boundary.
    The last term mildly prefers representatives farther from the n×n edge.
    """
    inds = np.nonzero(tensor)[0]
    if len(inds) <= 1:
        return (0.0, 0.0, 0)

    coords = build_coords(n)[inds]

    max_pair_dist = 0.0
    for a in range(len(coords)):
        for b in range(a + 1, len(coords)):
            max_pair_dist = max(max_pair_dist, float(np.linalg.norm(coords[a] - coords[b])))

    span = coords.max(axis=0) - coords.min(axis=0)
    bbox_area = float(span[0] * span[1])

    min_edge_dist = min(
        min(i, j, n - 1 - i, n - 1 - j)
        for i, j in (_defect_site_ij(int(idx), n) for idx in inds)
    )

    return (max_pair_dist, bbox_area, -min_edge_dist)


def choose_compact_representative(
    t_sub: np.ndarray,
    n: int,
    perms: np.ndarray,
) -> np.ndarray:
    """Choose a symmetry-equivalent representative compact without PBC.

    This keeps the canonical hash/label unchanged, but avoids embedding a
    boundary-wrapped n×n representative into a larger m×m host.
    """
    best_t = t_sub.copy()
    best_score = _compactness_score(best_t, n)
    seen = {best_t.tobytes()}

    for p in perms:
        cand = t_sub[p].copy()
        key = cand.tobytes()
        if key in seen:
            continue
        seen.add(key)

        score = _compactness_score(cand, n)
        if score < best_score:
            best_score = score
            best_t = cand

    return best_t


def _centroid_offset(t_sub: np.ndarray, n: int, m: int) -> tuple[int, int]:
    """Pick (offset_i, offset_j) so the defect cluster's cell-index centroid
    lands at the host centre (m-1)/2. Falls back to (m-n)//2 when there are
    no defects (pristine host)."""
    inds = np.nonzero(t_sub)[0]
    if len(inds) == 0:
        c = (m - n) // 2
        return c, c
    nsq = n * n
    sites = [(int(idx) % nsq) for idx in inds]
    ci = sum(s // n for s in sites) / len(sites)
    cj = sum(s %  n for s in sites) / len(sites)
    centre = (m - 1) / 2.0
    offset_i = int(round(centre - ci))
    offset_j = int(round(centre - cj))
    # Clamp so the n×n window still fits inside the m×m host.
    offset_i = max(0, min(m - n, offset_i))
    offset_j = max(0, min(m - n, offset_j))
    return offset_i, offset_j


def embed_tensor(t_sub: np.ndarray, n: int, m: int, centered: bool = False) -> np.ndarray:
    """Embed an n×n defect tensor in an m×m host supercell.

    t_sub: 1-D length 2n², encoding the sub-supercell C substitutions.
    Returns 1-D length 2m² tensor with the same defects copied into the
    host and pristine B/N (zeros) elsewhere.

    If centered=True and m > n, the embedding offset is chosen so the
    defect cluster's centroid (in cell-index space) lands at the host
    centre, clamped so the n×n window still fits inside m×m. Otherwise
    the block is placed at corner (0, 0).

    m == n short-circuits to a copy.
    """
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    if m == n:
        return t_sub.copy()

    nsq = n * n
    msq = m * m
    t = np.zeros(2 * msq, dtype=np.int8)

    if centered:
        offset_i, offset_j = _centroid_offset(t_sub, n, m)
    else:
        offset_i = offset_j = 0

    for i in range(n):
        for j in range(n):
            I = i + offset_i
            J = j + offset_j
            if t_sub[i * n + j]:
                t[I * m + J] = 1
            if t_sub[nsq + i * n + j]:
                t[msq + I * m + J] = 1
    return t


def motif_dirname(n: int, m: int, k_B: int, k_N: int, label: str) -> str:
    """Compose the output directory name per the naming rules."""
    if k_B == 0 and k_N == 0:
        return f"BN-{m}-{m}-1-pure"
    if m == n:
        return f"BN-{n}-{n}-1-{label}"
    return f"BN-{m}-{m}-1-N{n}-{label}"


def window_indices(n: int, m: int) -> np.ndarray:
    """Flat indices (length 2n²) of the n×n corner-window sites in a 2m² tensor.

    First n² entries map B-sublattice cells (i, j) ∈ [0,n)² to flat index
    i*m + j in the m×m B-channel; next n² do the same for the N-channel.
    """
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    msq = m * m
    idx = np.zeros(2 * n * n, dtype=np.int64)
    for i in range(n):
        for j in range(n):
            idx[i * n + j] = i * m + j
            idx[n * n + i * n + j] = msq + i * m + j
    return idx


def enumerate_window_motifs(
    n: int, m: int, k_B: int, k_N: int, perms_m: np.ndarray | None = None
) -> dict:
    """Enumerate defect configs inside the n×n corner window of an m×m host.

    Dedup uses equivalence (B): configs A, B are equivalent iff ∃ g ∈ G(m)
    with g·A = B and supp(g·A) ⊆ window. The canonical representative is
    the lex-min over the set of images g·A whose support stays inside the
    window, encoded as the 2n² window slice.

    Returns dict: canonical_bytes (length 2n²) → window tensor (length 2n²).
    """
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    if perms_m is None:
        perms_m = build_group(m)

    msq = m * m
    w_idx = window_indices(n, m)
    w_mask = np.zeros(2 * msq, dtype=bool)
    w_mask[w_idx] = True
    out_mask = ~w_mask

    nsq = n * n
    window_B = [int(w_idx[i]) for i in range(nsq)]
    window_N = [int(w_idx[nsq + i]) for i in range(nsq)]

    classes: dict[bytes, np.ndarray] = {}
    for sites_B in combinations(window_B, k_B):
        for sites_N in combinations(window_N, k_N):
            t = np.zeros(2 * msq, dtype=np.int8)
            for s in sites_B:
                t[s] = 1
            for s in sites_N:
                t[s] = 1

            best_key: bytes | None = None
            best_win: np.ndarray | None = None
            for p in perms_m:
                u = t[p]
                if u[out_mask].any():
                    continue
                u_win = u[w_idx]
                key = u_win.tobytes()
                if best_key is None or key < best_key:
                    best_key = key
                    best_win = u_win
            assert best_key is not None  # identity always satisfies the window check
            classes.setdefault(best_key, best_win)
    return classes


def _window_label(canon_bytes: bytes, k_B: int, k_N: int) -> str:
    if k_B == 0 and k_N == 0:
        return "pure"
    h = hashlib.sha1(canon_bytes).hexdigest()[:6]
    return f"cb{k_B}cn{k_N}_w{h}"


def generate(
    n: int,
    k_B: int,
    k_N: int,
    out_root: Path,
    bn_in_path: Path,
    m: int | None = None,
    algorithm: str = "canonical",
) -> list[Path]:
    if m is None:
        m = n
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    if algorithm not in ("canonical", "window"):
        raise ValueError(f"unknown algorithm: {algorithm!r}")
    lattice, atoms = parse_BN_in(bn_in_path)
    written = []

    if algorithm == "canonical":
        perms = build_group(n)
        classes = enumerate_motifs(n, k_B, k_N, perms)
        for canon_bytes, t_sub in sorted(classes.items()):
            label = summary_label(t_sub, n, perms)
            if m == n:
                t_write = t_sub
                t_full = embed_tensor(t_write, n, m)
                header = f"motif: {label}  (k_B={k_B}, k_N={k_N})"
            else:
                t_write = choose_compact_representative(t_sub, n, perms)
                t_full = embed_tensor(t_write, n, m, centered=True)
                header = (f"motif: {label}  (k_B={k_B}, k_N={k_N})  "
                          f"compact representative embedded n={n} in m={m} host")
            dirname = motif_dirname(n, m, k_B, k_N, label)
            out_path = out_root / dirname / "geometry.in"
            write_geometry(out_path, lattice, atoms, m, t_full, header=header)
            written.append(out_path)
        return written

    # algorithm == "window"
    perms_m = build_group(m)
    classes_w = enumerate_window_motifs(n, m, k_B, k_N, perms_m)
    for canon_bytes, t_window in sorted(classes_w.items()):
        label = _window_label(canon_bytes, k_B, k_N)
        t_full = embed_tensor(t_window, n, m, centered=(m > n))
        dirname = motif_dirname(n, m, k_B, k_N, label)
        out_path = out_root / dirname / "geometry.in"
        header = (f"motif: {label}  (k_B={k_B}, k_N={k_N})  "
                  f"window-enumerated, centred in m={m} host (n={n})")
        write_geometry(out_path, lattice, atoms, m, t_full, header=header)
        written.append(out_path)
    return written


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    bn_in = here / "BN.in"
    if not bn_in.exists():
        print(f"BN.in not found at {bn_in}", file=sys.stderr)
        return 2

    # Split positional vs flag args. The only flag we accept is --algorithm.
    algorithm = "canonical"
    positional: list[str] = []
    i = 1
    while i < len(argv):
        a = argv[i]
        if a == "--algorithm":
            if i + 1 >= len(argv):
                print("error: --algorithm requires a value", file=sys.stderr)
                return 2
            algorithm = argv[i + 1]
            i += 2
            continue
        if a.startswith("--algorithm="):
            algorithm = a.split("=", 1)[1]
            i += 1
            continue
        positional.append(a)
        i += 1

    if algorithm not in ("canonical", "window"):
        print(f"error: unknown --algorithm {algorithm!r}", file=sys.stderr)
        return 2
    if len(positional) not in (2, 3, 4):
        print(__doc__, file=sys.stderr)
        return 2
    n = int(positional[0])
    k = int(positional[1])
    out_root = Path(positional[2]) if len(positional) >= 3 else here / "generated"
    m = int(positional[3]) if len(positional) == 4 else n
    if m < n:
        print(f"error: m ({m}) must be >= n ({n})", file=sys.stderr)
        return 2
    splits = [(k_B, k - k_B) for k_B in range(k + 1)]

    total = 0
    for k_B, k_N in splits:
        paths = generate(n, k_B, k_N, out_root, bn_in, m=m, algorithm=algorithm)
        print(f"# (k_B={k_B}, k_N={k_N}): {len(paths)} motif(s)")
        for p in paths:
            print(f"  {p.relative_to(here) if p.is_relative_to(here) else p}")
        total += len(paths)
    embedding = "" if m == n else f" (n={n} embedded in m={m})"
    print(f"# total: {total} geometry.in files written under {out_root}"
          f"{embedding} [algorithm={algorithm}]")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
