"""Generate FHI-aims geometry.in files for every symmetry-distinct motif of
a given n×n hBN supercell with a specified defect count, optionally embedded
in a larger m×m host supercell.

Enumerates canonical classes on the n×n sub-supercell (cheap), then embeds
each motif in an m×m host where m >= n. For m > n, a compact
symmetry-equivalent representative is chosen before embedding so that motifs
that are compact only through the n×n periodic boundary do not get split in
the larger host. The canonical hash stays computed on the n×n tensor so hash
labels are stable across host sizes.

Output paths:
    {OUT}/BN-{m}-{m}-1-pure/geometry.in          when k = 0
    {OUT}/BN-{n}-{n}-1-{label}/geometry.in       when m == n and k > 0
    {OUT}/BN-{m}-{m}-1-N{n}-{label}/geometry.in  when m > n and k > 0

Usage:
    python generate_geometry.py <n> <k> [out_dir [m]]

Generates all (k_B, k_N) splits with k_B + k_N = k.
OUT_DIR defaults to 'generated/'; m defaults to n (no embedding).
"""

import sys
from pathlib import Path

import numpy as np

from canonicalize import (
    build_coords,
    build_group,
    enumerate_motifs,
    summary_label,
)
from tools.render_supercell import annotate, render_from_tensor


def parse_BN_in(path: Path) -> tuple[list, list]:
    """Return (lattice_vectors[3][3], atom_info[2]) where each atom is
    (species, frac_x, frac_y, frac_z)."""
    lattice = []
    atoms = []
    with open(path) as f:
        for line in f:
            parts = line.split()
            if not parts or parts[0].startswith("#"):
                continue
            if parts[0] == "lattice_vector":
                lattice.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "atom_frac":
                atoms.append((parts[4], float(parts[1]), float(parts[2]), float(parts[3])))
    assert len(lattice) == 3, f"Expected 3 lattice_vector lines, got {len(lattice)}"
    assert len(atoms) == 2, f"Expected 2 atoms in primitive BN.in, got {len(atoms)}"
    # Order atoms so that B comes first, N second (matches Maciej convention).
    atoms.sort(key=lambda a: 0 if a[0] == "B" else 1)
    return lattice, atoms


def write_geometry(
    out_path: Path,
    lattice: list,
    primitive_atoms: list,
    n: int,
    tensor,
    header: str = "",
):
    """Write a geometry.in for an n×n supercell with C substitutions per `tensor`.

    tensor: 1-D length 2n², with 1 at (channel, i, j) for each C.
      - channel 0 = B-sublattice substitution
      - channel 1 = N-sublattice substitution
    """
    (b_sp, b_fx, b_fy, b_fz), (n_sp, n_fx, n_fy, n_fz) = primitive_atoms
    assert b_sp == "B" and n_sp == "N"

    # Supercell lattice vectors (z untouched)
    a1 = [lattice[0][k] * n for k in range(3)]
    a2 = [lattice[1][k] * n for k in range(3)]
    a3 = lattice[2]

    lines = []
    if header:
        lines.append(f"# {header}")
    lines.append(f"# Generated by generate_geometry.py for n={n} supercell")
    lines.append("#")
    lines.append("# Supercell view (armchair-vertical, a₂ slants down-right):")
    for line in render_from_tensor(tensor, n).split("\n"):
        lines.append(f"#   {line}")
    for line in annotate(tensor=tensor, n=n).split("\n"):
        lines.append(f"# {line}")
    lines.append("#")
    for vec in (a1, a2, a3):
        lines.append(
            f"lattice_vector {vec[0]:18.10f} {vec[1]:18.10f} {vec[2]:18.10f}"
        )

    m = n * n
    for i in range(n):
        for j in range(n):
            # B at supercell-frac ((i + b_fx)/n, (j + b_fy)/n, b_fz)
            sp_B = "C" if tensor[i * n + j] else "B"
            fx_B = (i + b_fx) / n
            fy_B = (j + b_fy) / n
            lines.append(
                f"atom_frac      {fx_B:18.10f} {fy_B:18.10f} {b_fz:18.10f} {sp_B}"
            )
            sp_N = "C" if tensor[m + i * n + j] else "N"
            fx_N = (i + n_fx) / n
            fy_N = (j + n_fy) / n
            lines.append(
                f"atom_frac      {fx_N:18.10f} {fy_N:18.10f} {n_fz:18.10f} {sp_N}"
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


def _defect_site_ij(idx: int, n: int) -> tuple[int, int]:
    """Return the (i, j) cell index of a flat B/N defect-site index."""
    nsq = n * n
    site = idx if idx < nsq else idx - nsq
    return site // n, site % n


def _compactness_score(tensor: np.ndarray, n: int) -> tuple[float, float, int]:
    """Score a representative by non-periodic compactness. Lower is better.

    The first term catches motifs split across the artificial n×n boundary.
    The last term mildly prefers representatives farther from the n×n edge.
    """
    inds = np.nonzero(tensor)[0]
    if len(inds) <= 1:
        return (0.0, 0.0, 0)

    coords = build_coords(n)[inds]

    max_pair_dist = 0.0
    for a in range(len(coords)):
        for b in range(a + 1, len(coords)):
            max_pair_dist = max(max_pair_dist, float(np.linalg.norm(coords[a] - coords[b])))

    span = coords.max(axis=0) - coords.min(axis=0)
    bbox_area = float(span[0] * span[1])

    min_edge_dist = min(
        min(i, j, n - 1 - i, n - 1 - j)
        for i, j in (_defect_site_ij(int(idx), n) for idx in inds)
    )

    return (max_pair_dist, bbox_area, -min_edge_dist)


def choose_compact_representative(
    t_sub: np.ndarray,
    n: int,
    perms: np.ndarray,
) -> np.ndarray:
    """Choose a symmetry-equivalent representative compact without PBC.

    This keeps the canonical hash/label unchanged, but avoids embedding a
    boundary-wrapped n×n representative into a larger m×m host.
    """
    best_t = t_sub.copy()
    best_score = _compactness_score(best_t, n)
    seen = {best_t.tobytes()}

    for p in perms:
        cand = t_sub[p].copy()
        key = cand.tobytes()
        if key in seen:
            continue
        seen.add(key)

        score = _compactness_score(cand, n)
        if score < best_score:
            best_score = score
            best_t = cand

    return best_t


def embed_tensor(t_sub: np.ndarray, n: int, m: int, centered: bool = False) -> np.ndarray:
    """Embed an n×n defect tensor in an m×m host supercell.

    t_sub: 1-D length 2n², encoding the sub-supercell C substitutions.
    Returns 1-D length 2m² tensor with the same defects copied into the
    host and pristine B/N (zeros) elsewhere.

    If centered=True and m > n, the n×n block is placed near the centre of
    the m×m host; otherwise it is placed at corner (0,0).

    m == n short-circuits to a copy.
    """
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    if m == n:
        return t_sub.copy()

    nsq = n * n
    msq = m * m
    t = np.zeros(2 * msq, dtype=np.int8)

    offset_i = (m - n) // 2 if centered else 0
    offset_j = (m - n) // 2 if centered else 0

    for i in range(n):
        for j in range(n):
            I = i + offset_i
            J = j + offset_j
            if t_sub[i * n + j]:
                t[I * m + J] = 1
            if t_sub[nsq + i * n + j]:
                t[msq + I * m + J] = 1
    return t


def motif_dirname(n: int, m: int, k_B: int, k_N: int, label: str) -> str:
    """Compose the output directory name per the naming rules."""
    if k_B == 0 and k_N == 0:
        return f"BN-{m}-{m}-1-pure"
    if m == n:
        return f"BN-{n}-{n}-1-{label}"
    return f"BN-{m}-{m}-1-N{n}-{label}"


def generate(
    n: int,
    k_B: int,
    k_N: int,
    out_root: Path,
    bn_in_path: Path,
    m: int | None = None,
) -> list[Path]:
    if m is None:
        m = n
    if m < n:
        raise ValueError(f"m ({m}) must be >= n ({n})")
    lattice, atoms = parse_BN_in(bn_in_path)
    perms = build_group(n)
    classes = enumerate_motifs(n, k_B, k_N, perms)
    written = []
    for canon_bytes, t_sub in sorted(classes.items()):
        label = summary_label(t_sub, n, perms)
        if m == n:
            t_write = t_sub
            t_full = embed_tensor(t_write, n, m)
        else:
            # Keep label/hash from the canonical n×n class, but write a
            # compact symmetry-equivalent representative into the m×m host.
            t_write = choose_compact_representative(t_sub, n, perms)
            t_full = embed_tensor(t_write, n, m, centered=True)
        dirname = motif_dirname(n, m, k_B, k_N, label)
        out_path = out_root / dirname / "geometry.in"
        if m == n:
            header = f"motif: {label}  (k_B={k_B}, k_N={k_N})"
        else:
            header = (f"motif: {label}  (k_B={k_B}, k_N={k_N})  "
                      f"compact representative embedded n={n} in m={m} host")
        write_geometry(
            out_path, lattice, atoms, m, t_full, header=header,
        )
        written.append(out_path)
    return written


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    bn_in = here / "BN.in"
    if not bn_in.exists():
        print(f"BN.in not found at {bn_in}", file=sys.stderr)
        return 2

    if len(argv) not in (3, 4, 5):
        print(__doc__, file=sys.stderr)
        return 2
    n = int(argv[1])
    k = int(argv[2])
    out_root = Path(argv[3]) if len(argv) >= 4 else here / "generated"
    m = int(argv[4]) if len(argv) == 5 else n
    if m < n:
        print(f"error: m ({m}) must be >= n ({n})", file=sys.stderr)
        return 2
    splits = [(k_B, k - k_B) for k_B in range(k + 1)]

    total = 0
    for k_B, k_N in splits:
        paths = generate(n, k_B, k_N, out_root, bn_in, m=m)
        print(f"# (k_B={k_B}, k_N={k_N}): {len(paths)} motif(s)")
        for p in paths:
            print(f"  {p.relative_to(here) if p.is_relative_to(here) else p}")
        total += len(paths)
    embedding = "" if m == n else f" (n={n} embedded in m={m})"
    print(f"# total: {total} geometry.in files written under {out_root}{embedding}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
