"""Generate FHI-aims geometry.in files for every symmetry-distinct motif of
a given n×n hBN supercell with a specified defect count.

Reads BN.in for the primitive cell. For each canonical class produced by
enumerate_motifs(n, k_B, k_N), writes:

    {OUT_DIR}/BN-{n}-{n}-1-{label}/geometry.in

where {label} is the human-readable summary (e.g. 'pure', 'benzene',
'cb1cn1_9cd6bb').

Usage:
    python generate_geometry.py <n> <k> [out_dir]

Generates all (k_B, k_N) splits with k_B + k_N = k.
OUT_DIR defaults to 'generated/'.
"""

import sys
from pathlib import Path

from canonicalize import (
    build_group,
    enumerate_motifs,
    motif_dirname,
    summary_label,
)


def parse_BN_in(path: Path) -> tuple[list, list]:
    """Return (lattice_vectors[3][3], atom_info[2]) where each atom is
    (species, frac_x, frac_y, frac_z)."""
    lattice = []
    atoms = []
    with open(path) as f:
        for line in f:
            parts = line.split()
            if not parts or parts[0].startswith("#"):
                continue
            if parts[0] == "lattice_vector":
                lattice.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "atom_frac":
                atoms.append((parts[4], float(parts[1]), float(parts[2]), float(parts[3])))
    assert len(lattice) == 3, f"Expected 3 lattice_vector lines, got {len(lattice)}"
    assert len(atoms) == 2, f"Expected 2 atoms in primitive BN.in, got {len(atoms)}"
    # Order atoms so that B comes first, N second (matches Maciej convention).
    atoms.sort(key=lambda a: 0 if a[0] == "B" else 1)
    return lattice, atoms


def write_geometry(
    out_path: Path,
    lattice: list,
    primitive_atoms: list,
    n: int,
    tensor,
    header: str = "",
):
    """Write a geometry.in for an n×n supercell with C substitutions per `tensor`.

    tensor: 1-D length 2n², with 1 at (channel, i, j) for each C.
      - channel 0 = B-sublattice substitution
      - channel 1 = N-sublattice substitution
    """
    (b_sp, b_fx, b_fy, b_fz), (n_sp, n_fx, n_fy, n_fz) = primitive_atoms
    assert b_sp == "B" and n_sp == "N"

    # Supercell lattice vectors (z untouched)
    a1 = [lattice[0][k] * n for k in range(3)]
    a2 = [lattice[1][k] * n for k in range(3)]
    a3 = lattice[2]

    lines = []
    if header:
        lines.append(f"# {header}")
    lines.append(f"# Generated by generate_geometry.py for n={n} supercell")
    for vec in (a1, a2, a3):
        lines.append(
            f"lattice_vector {vec[0]:18.10f} {vec[1]:18.10f} {vec[2]:18.10f}"
        )

    m = n * n
    for i in range(n):
        for j in range(n):
            # B at supercell-frac ((i + b_fx)/n, (j + b_fy)/n, b_fz)
            sp_B = "C" if tensor[i * n + j] else "B"
            fx_B = (i + b_fx) / n
            fy_B = (j + b_fy) / n
            lines.append(
                f"atom_frac      {fx_B:18.10f} {fy_B:18.10f} {b_fz:18.10f} {sp_B}"
            )
            sp_N = "C" if tensor[m + i * n + j] else "N"
            fx_N = (i + n_fx) / n
            fy_N = (j + n_fy) / n
            lines.append(
                f"atom_frac      {fx_N:18.10f} {fy_N:18.10f} {n_fz:18.10f} {sp_N}"
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


def generate(
    n: int,
    k_B: int,
    k_N: int,
    out_root: Path,
    bn_in_path: Path,
) -> list[Path]:
    lattice, atoms = parse_BN_in(bn_in_path)
    perms = build_group(n)
    classes = enumerate_motifs(n, k_B, k_N, perms)
    written = []
    for canon_bytes, tensor in sorted(classes.items()):
        label = summary_label(tensor, n, perms)
        dirname = f"BN-{n}-{n}-1-{label}"
        out_dir = out_root / dirname
        out_path = out_dir / "geometry.in"
        write_geometry(
            out_path, lattice, atoms, n, tensor,
            header=f"motif: {label}  (k_B={k_B}, k_N={k_N})",
        )
        written.append(out_path)
    return written


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    bn_in = here / "BN.in"
    if not bn_in.exists():
        print(f"BN.in not found at {bn_in}", file=sys.stderr)
        return 2

    if len(argv) not in (3, 4):
        print(__doc__, file=sys.stderr)
        return 2
    n = int(argv[1])
    k = int(argv[2])
    out_root = Path(argv[3]) if len(argv) == 4 else here / "generated"
    splits = [(k_B, k - k_B) for k_B in range(k + 1)]

    total = 0
    for k_B, k_N in splits:
        paths = generate(n, k_B, k_N, out_root, bn_in)
        print(f"# (k_B={k_B}, k_N={k_N}): {len(paths)} motif(s)")
        for p in paths:
            print(f"  {p.relative_to(here) if p.is_relative_to(here) else p}")
        total += len(paths)
    print(f"# total: {total} geometry.in files written under {out_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
